# Generated by Django 5.0.6 on 2024-05-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("data_type", models.CharField(max_length=50)),
                ("data", models.JSONField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("latitude", "longitude", "data_type")},
            },
        ),
    ]
